
import { Inter } from 'next/font/google'
import '../../public/font/style.css'
import './styles/global.css'
import ThemeRegistry from '@/app/utils/ThemeRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
	return (

		<html lang="fa" dir="rtl">
			<meta name="theme-color" media="(prefers-color-scheme: light)" content="#5274F9" />
			<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#5274F9" />
			<body className={inter.className}>
				<ThemeRegistry options={{ key: 'mui-theme' }}>{children}</ThemeRegistry>
			</body>
		</html>

	)
}
